version: '2.1'

services:
  mysql:
    image: mysql:5.7
    command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testtest
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
  php:
    build: build/php
    ports:
      - "${DOCKER_MAP_PORT}:80"
      #- "9000:9000"
      #- "8877:8877"
    volumes:
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    environment:
      - TZ=Asia/Tokyo
    links:
      - mysql:mysql
